spring.application.name=ticketing

# ===============================
# 1. Datasource (DB ?? ??)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://moon-core:5433/NOL
spring.datasource.username=nol_2025
spring.datasource.password=NOL_2025!@#

# ===============================
# 2. JPA / Hibernate ??
# ===============================

# DDL ?? ?? ?? (create, create-drop, update, validate, none,???? ??)
# spring.jpa.hibernate.ddl-auto=update

# ???? SQL ??? ??? ??
spring.jpa.show-sql=true

# ??? ???? SQL ??? ?? ?? ???
spring.jpa.properties.hibernate.format_sql=true

# ??? ??? ????(?, ?)? ?? ?? ???? ??
spring.jpa.properties.hibernate.use_sql_comments=true
# ===============================
# 3. Hibernate ?? ?? (???? ? ?? ??)
# ===============================
# ??? ? ? ????? ?? ???? ?? ?? (TRACE ??)
logging.level.org.hibernate.orm.jdbc.bind=trace

# DB?? ???? ?? ?(Result ???)? ?? (TRACE ??)
logging.level.org.hibernate.orm.jdbc.extract=trace

# ================================
# 4. ??? JSP ??(2026-03-09)
# ================================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


# ================================
# 5. ??? ????  ??(2026-03-15)
# ================================
decorator.datasource.p6spy.multiline=true

# ================================
# 5. ??? ????? ?? ??(2026-03-22)
# ================================
app.upload.dir=${user.home}/ticketing-uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB